In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('car_data.csv')
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [7]:
df["owner"].isnull().sum()

0

In [8]:
df["name"].isnull().sum()

0

In [9]:
df["year"].isnull().sum()

0

In [10]:
df["selling_price"].isnull().sum()

0

In [11]:
df["km_driven"].isnull().sum()

0

In [12]:
df["fuel"].isnull().sum()

0

In [13]:
df["seller_type"].isnull().sum()

0

In [14]:
df["transmission"].isnull().sum()

0

In [15]:
df["owner"].value_counts()

First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: owner, dtype: int64

In [16]:
x = df.iloc[: , [1,3,4,6]].values
y = df.iloc[:, 2].values

In [18]:
x

array([[2007, 70000, 'Petrol', 'Manual'],
       [2007, 50000, 'Petrol', 'Manual'],
       [2012, 100000, 'Diesel', 'Manual'],
       ...,
       [2009, 83000, 'Petrol', 'Manual'],
       [2016, 90000, 'Diesel', 'Manual'],
       [2016, 40000, 'Petrol', 'Manual']], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,2] = lb.fit_transform(x[:,2])
lb1 = LabelEncoder()
x[:,3] = lb.fit_transform(x[:,3])

In [20]:
x[:,2]

array([4, 4, 1, ..., 4, 1, 4], dtype=object)

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

print(x_train[:,:])

[[2015 175000 1 1]
 [2012 170000 1 1]
 [2006 110000 4 1]
 ...
 [2016 22000 4 1]
 [2015 70000 1 1]
 [2013 62000 4 1]]


In [31]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators= 2000, random_state=42)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=2000, random_state=42)

In [32]:
accuracy = regressor.score(x_test, y_test)
print(accuracy*100, '%')

75.79968697446978 %


In [34]:
import pickle
pickle.dump(regressor,open('regressor.pkl','wb'))
pickle.dump(lb,open('lb','wb'))
pickle.dump(lb1,open('lb1','wb'))